FROM eclipse-temurin:11-jre-jammy

WORKDIR /usr/local/openncp-tsam-exporter

COPY openncp-tsam-exporter.jar /usr/local/openncp-tsam-exporter/openncp-tsam-exporter.jar

CMD ["java", "-jar", "openncp-tsam-exporter.jar"]
