apiVersion: apps/v1
kind: Deployment
metadata:
  name: ehealth-portal-frontend
  namespace: openncp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ehealth-portal-frontend
  template:
    metadata:
      labels:
        app: ehealth-portal-frontend
    spec:
      containers:
      - name: ehealth-portal-frontend
        image: ghcr.io/ucy-ehealthlab/ehealth-portal-frontend:1.1.0
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: TLS_KEYSTORE_PATH
          value: "/opt/epsos-configuration/certs/cy_tls.jks"
        - name: TLS_TRUSTSTORE_PATH
          value: "/opt/epsos-configuration/certs/truststore.jks"
        - name: TLS_KEY_ALIAS
          valueFrom:
            secretKeyRef:
              name: openncp-secret
              key: TLS_KEY_ALIAS
        - name: TLS_KEYSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: openncp-secret
              key: TLS_KEYSTORE_PWD
        - name: TLS_TRUSTSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: openncp-secret
              key: TLS_TRUSTSTORE_PWD
        - name: JAVA_OPTS
          value: "
            -Dtls_key_alias=${TLS_KEY_ALIAS}
            -Dtls_keystore_pwd=${TLS_KEYSTORE_PWD}
            -Dtls_keystore_path=${TLS_KEYSTORE_PATH}
            -Dtls_truststore_pwd=${TLS_TRUSTSTORE_PWD}
            -Dtls_truststore_path=${TLS_TRUSTSTORE_PATH}"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        volumeMounts:
        - name: epsos-configuration-volume
          mountPath: /opt/epsos-configuration
        # - name: openncp-server-logs
        #   mountPath: /usr/local/tomcat/logs
      volumes:
      - name: epsos-configuration-volume
        persistentVolumeClaim:
          claimName: epsos-configuration-pvc
      # - name: openncp-server-logs
      #   emptyDir: {}
