wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Aat%3Ancp-idp/ -O services/at-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Afi%3Ancp-idp/ -O services/fi-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Apt%3Ancp-idp/ -O services/pt-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Amt%3Ancp-idp/ -O services/mt-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Anl%3Ancp-idp/ -O services/nl-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Aes%3Ancp-idp/ -O services/es-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Aee%3Ancp-idp/ -O services/ee-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Ait%3Ancp-idp/ -O services/it-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Ahr%3Ancp-idp/ -O services/hr-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Acz%3Ancp-idp/ -O services/cz-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Agr%3Ancp-idp/ -O services/gr-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Alu%3Ancp-idp/ -O services/lu-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Apl%3Ancp-idp/ -O services/pl-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Ase%3Ancp-idp/ -O services/se-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Acy%3Ancp-idp/ -O services/cy-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Aie%3Ancp-idp/ -O services/ie-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Abe%3Ancp-idp/ -O services/be-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Ach%3Ancp-idp/ -O services/ch-services.xml
wget https://smp-test.publisher.ehealth.testa.eu/ehealth-participantid-qns%3A%3Aurn%3Aehealth%3Aie%3Ancp-idp/ -O services/ie-services.xml
