debug: false
logging:
  level:
     org.hibernate: ERROR
     org.springframework.web.client: DEBUG
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      naming:
        physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    url: jdbc:mysql://127.0.0.1/ehealth_properties?useSSL=false
    username: eHealthUser
    password: eHealthPwd
    driver-class-name: com.mysql.jdbc.Driver
openncp:
  property-file:
    path: /opt/ehealth-openncp/openncp-configuration-utility/openncp-configuration.properties
profiles:
   active: mysql
