debug: false
logging:
  level:
     org.hibernate: ERROR
     org.springframework.web.client: DEBUG
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    hibernate:
      naming:
        physical_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/ehealth_properties?useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
openncp:
  property-file:
    path: openncp-configuration.properties
profiles:
   active: mysql
