FROM eclipse-temurin:11-jre-jammy

WORKDIR /usr/local/openncp-configuration-utility

COPY openncp-configuration-utility.jar /usr/local/openncp-configuration-utility/openncp-configuration-utility.jar

CMD ["java", "-jar", "openncp-configuration-utility.jar"]
