version: "3.9"
services:
  mysql:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: rootpassword
        MYSQL_USER: ${MYSQL_USERNAME}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/startup-scripts:/docker-entrypoint-initdb.d:ro
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./logs/mysql:/var/log/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - openncp

  openncp-client:
    container_name: openncp-client
    image: openncp-client:5.2.4
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8443:8443"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      EPSOS_PROPS_PATH: ${EPSOS_PROPS_PATH}
      CATALINA_OPTS: "$CATALINA_OPTS -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties -Dfile.encoding=UTF-8"
      JAVA_OPTS: "-DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties -Dfile.encoding=UTF-8 -Dmysql_host=${MYSQL_HOST} -Dmysql_port=${MYSQL_PORT} -Dmysql_username=${MYSQL_USERNAME} -Dmysql_password=${MYSQL_PASSWORD}"
      #https://stackoverflow.com/questions/13956651/externalizing-tomcat-webapp-config-from-war-file
      #
      LOGGING_LEVEL_ROOT: DEBUG
      GTW_TLS_CLIENT_CERT_ALIAS: ${GTW_TLS_CLIENT_CERT_ALIAS}
      GTW_TLS_CLIENT_CERT_PWD: ${GTW_TLS_CLIENT_CERT_PWD}
      GTW_TLS_CLIENT_KEYSTORE_PATH: ${GTW_TLS_CLIENT_KEYSTORE_PATH}
      GTW_TLS_CLIENT_KEYSTORE_PWD: ${GTW_TLS_CLIENT_KEYSTORE_PWD}
      GTW_TRUSTSTORE_PATH: ${GTW_TRUSTSTORE_PATH}
      GTW_TRUSTSTORE_PWD: ${GTW_TRUSTSTORE_PWD}
    volumes:
      - ./epsos-configuration:/opt/epsos-configuration
      - ./logs/openncp-client:/usr/local/tomcat/logs
    networks:
      - openncp

  openncp-server:
    container_name: openncp-server
    image: openncp-server:5.2.4
    ports:
      - "8081:8080"
      - "8444:8443"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      EPSOS_PROPS_PATH: "/opt/epsos-configuration/"
      CATALINA_OPTS: "$CATALINA_OPTS -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties -Dfile.encoding=UTF-8"
      JAVA_OPTS: "-DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties -Dfile.encoding=UTF-8 -Dmysql_host=${MYSQL_HOST} -Dmysql_port=${MYSQL_PORT} -Dmysql_username=${MYSQL_USERNAME} -Dmysql_password=${MYSQL_PASSWORD}"
      #https://stackoverflow.com/questions/13956651/externalizing-tomcat-webapp-config-from-war-file
      #
      LOGGING_LEVEL_ROOT: DEBUG
      
    volumes:
      - ./epsos-configuration:/opt/epsos-configuration
      - ./logs/openncp-server:/usr/local/tomcat/logs
    networks:
      - openncp
      
      
  openncp-gateway-backend:
    container_name: openncp-gateway-backend
    image: openncp-gateway-backend:5.2.4
    ports:
      - "8082:8080"
      - "8445:8443"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      EPSOS_PROPS_PATH: "/opt/epsos-configuration/"
      CATALINA_OPTS: "$CATALINA_OPTS -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties -Dfile.encoding=UTF-8"
      JAVA_OPTS: "-DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties -Dfile.encoding=UTF-8 -Dmysql_host=${MYSQL_HOST} -Dmysql_port=${MYSQL_PORT} -Dmysql_username=${MYSQL_USERNAME} -Dmysql_password=${MYSQL_PASSWORD}"
      #https://stackoverflow.com/questions/13956651/externalizing-tomcat-webapp-config-from-war-file
      #
      LOGGING_LEVEL_ROOT: DEBUG
    volumes:
      - ./epsos-configuration:/opt/epsos-configuration
      - ./logs/openncp-gateway-backend:/usr/local/tomcat/logs
      - ./tomcat-configuration/openncp-gateway-backend/tomcat-config:/usr/local/tomcat/conf/Catalina/localhost
      - ./tomcat-configuration/openncp-gateway-backend/opt/openncp-gateway-backend-config:/opt/tomcat-configuration
    networks:
      - openncp
      
  openncp-gateway-frontend:
    container_name: openncp-gateway-frontend
    image: docker.io/library/openncp-gateway-frontend:latest
    ports:
      - "8083:80"
      - "8446:443"
    depends_on:
      - openncp-gateway-backend
    networks:
      - openncp
volumes:
  persistent:
  mysql-data:
  portainer-data:

networks:
  openncp:
    external: false
    name: openncp
