USE ehealth_properties;
DROP 
  TABLE IF EXISTS EHNCP_PROPERTY;
CREATE TABLE EHNCP_PROPERTY (
  `NAME` VARCHAR(255) NOT NULL, 
  `VALUE` VARCHAR(255) NULL DEFAULT NULL, 
  `IS_SMP` BIT(1) NULL DEFAULT b'0', 
  PRIMARY KEY (`NAME`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
