USE ehealth_properties;
CREATE TABLE IF NOT EXISTS EHNCP_ROLE (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  NAME VARCHAR(50) NOT NULL, 
  DESCRIPTION VARCHAR(255) NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE KEY role (NAME)
) DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS EHNCP_USER (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT, 
  USERNAME VARCHAR(50) NOT NULL, 
  PASSWORD VARCHAR(255) NOT NULL, 
  ENABLED BIT(1) NOT NULL, 
  EMAIL VARCHAR(45) DEFAULT NULL, 
  VERIFICATION_CODE VARCHAR(64) DEFAULT NULL, 
  RESET_DATE datetime(6) DEFAULT NULL, 
  RESET_KEY varchar(255) DEFAULT NULL, 
  PRIMARY KEY (id)
) DEFAULT CHARSET = UTF8;
CREATE TABLE IF NOT EXISTS EHNCP_USER_ROLE (
  USER_ID BIGINT(20) NOT NULL, 
  ROLE_ID BIGINT(20) NOT NULL, 
  KEY FK_USER_ID (USER_ID), 
  KEY FK_ROLE_ID (ROLE_ID), 
  CONSTRAINT FK_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES EHNCP_ROLE (ID), 
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES EHNCP_USER (ID)
) DEFAULT CHARSET = UTF8;
INSERT INTO EHNCP_ROLE (ID, NAME, DESCRIPTION) 
VALUES 
  (1, 'GTW_ADMIN', 'Admin');
INSERT INTO EHNCP_ROLE (ID, NAME, DESCRIPTION) 
VALUES 
  (
    2, 'GTW_ATNA_ADMIN', 'ATNA Admin'
  );
INSERT INTO EHNCP_ROLE (ID, NAME, DESCRIPTION) 
VALUES 
  (
    3, 'GTW_EADC_ADMIN', 'EADC Admin'
  );
INSERT INTO EHNCP_ROLE (ID, NAME, DESCRIPTION) 
VALUES 
  (4, 'GTW_NCP_ADMIN', 'NCP Admin');
INSERT INTO EHNCP_ROLE (ID, NAME, DESCRIPTION) 
VALUES 
  (5, 'GTW_SMP_ADMIN', 'SMP Admin');
INSERT INTO EHNCP_USER (
  ID, USERNAME, PASSWORD, ENABLED, VERIFICATION_CODE, 
  EMAIL, RESET_DATE, RESET_KEY
) 
VALUES 
  (
    1, 'admin', '$2a$10$8r1ag0oDuDpgYXGMmoUOteYxMsnMmC6ZarzvqQ68J5GBrzF4Opz9u', 
    1, NULL, 'admin@email.com', NULL, 
    NULL
  );
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) 
VALUES 
  (1, 1);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) 
VALUES 
  (1, 2);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) 
VALUES 
  (1, 3);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) 
VALUES 
  (1, 4);
INSERT INTO EHNCP_USER_ROLE (USER_ID, ROLE_ID) 
VALUES 
  (1, 5);
