USE ehealth_properties;

CREATE TABLE IF NOT EXISTS EHNCP_ANOMALY (
ID bigint(20) NOT NULL AUTO_INCREMENT,
DESCRIPTION varchar(500) DEFAULT NULL,
TYPE varchar(20) DEFAULT NULL,
EVENT_DATE datetime DEFAULT NULL,
EVENT_START_DATE datetime DEFAULT NULL,
EVENT_END_DATE datetime DEFAULT NULL,
PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
