apiVersion: v1
kind: Service
metadata:
  name: ehealth-portal-backend-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    # nodePort: 30004 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  - name: https
    port: 8443
    targetPort: 8443
    # nodePort: 30005  # This is the port that will be exposed to the outside world (Adjust this to your needs)
  selector:
    app: ehealth-portal-backend
