apiVersion: v1
kind: Service
metadata:
  name: ehealth-portal-backend-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 36080
  - name: https
    port: 8443
    targetPort: 8443
    nodePort: 36443
  selector:
    app: ehealth-portal-backend
