apiVersion: v1
kind: Service
metadata:
  name: openncp-client-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 7080
    targetPort: 7080
    nodePort: 31080
  - name: https
    port: 7443
    targetPort: 7443
    nodePort: 31443
  selector:
    app: openncp-client
