apiVersion: v1
kind: Service
metadata:
  name: openncp-client-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 7080
    targetPort: 7080
    # nodePort: 30002 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  - name: https
    port: 7443
    targetPort: 7443
    # nodePort: 30003 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  selector:
    app: openncp-client
