apiVersion: v1
kind: Service
metadata:
  name: openncp-gateway-backend-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 11080
    targetPort: 11080
    # nodePort: 30008 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  - name: https
    port: 11443
    targetPort: 11443
    # nodePort: 30009 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  selector:
    app: openncp-gateway-backend
