apiVersion: apps/v1
kind: Deployment
metadata:
  name: openncp-trc-sts
  namespace: openncp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openncp-trc-sts
  template:
    metadata:
      labels:
        app: openncp-trc-sts
    spec:
      containers:
      - name: openncp-trc-sts
        image: docker.io/3ahealth/openncp-trc-sts:7.1.0
        ports:
        - containerPort: 10080
        - containerPort: 10443
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: EPSOS_PROPS_PATH
          value: "/opt/epsos-configuration/"
        - name: CATALINA_OPTS
          value: "
            -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties
            -Dfile.encoding=UTF-8"
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: TLS_KEYSTORE_PATH
          value: "/opt/epsos-configuration/certs/cy_tls.jks"
        - name: TLS_TRUSTSTORE_PATH
          value: "/opt/epsos-configuration/certs/truststore.jks"
        - name: TLS_KEY_ALIAS
          valueFrom:
            secretKeyRef:
              name: openncp-secret
              key: TLS_KEY_ALIAS
        - name: TLS_KEYSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: openncp-secret
              key: TLS_KEYSTORE_PWD
        - name: TLS_TRUSTSTORE_PWD
          valueFrom:
            secretKeyRef:
              name: openncp-secret
              key: TLS_TRUSTSTORE_PWD
        - name: JAVA_OPTS
          value: "
            -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties
            -Dfile.encoding=UTF-8
            -Dmysql_host=${MYSQL_HOST}
            -Dmysql_port=${MYSQL_PORT}
            -Dmysql_username=${MYSQL_USERNAME}
            -Dmysql_password=${MYSQL_PASSWORD}
            -Dtls_key_alias=${TLS_KEY_ALIAS}
            -Dtls_keystore_pwd=${TLS_KEYSTORE_PWD}
            -Dtls_keystore_path=${TLS_KEYSTORE_PATH}
            -Dtls_truststore_pwd=${TLS_TRUSTSTORE_PWD}
            -Dtls_truststore_path=${TLS_TRUSTSTORE_PATH}"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        volumeMounts:
        - name: epsos-configuration-volume
          mountPath: /opt/epsos-configuration
        # - name: openncp-trc-sts-logs
        #   mountPath: /usr/local/tomcat/logs
      volumes:
      - name: epsos-configuration-volume
        persistentVolumeClaim:
          claimName: epsos-configuration-pvc
      # - name: openncp-trc-sts-logs
      #   emptyDir: {}