debug: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/ehealth_ltrdb?useSSL=false
    username: openncpUser
    password: openncpPass
    driver-class-name: com.mysql.jdbc.Driver
openncp:
  root:
    path: ../
