apiVersion: v1
kind: Service
metadata:
  name: openncp-gateway-frontend-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 12080
    targetPort: 12080
    nodePort: 30010
  - name: https
    port: 12443
    targetPort: 12443
    nodePort: 30011
  selector:
    app: openncp-gateway-frontend
