apiVersion: v1
kind: Service
metadata:
  name: openncp-openatna-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - name: http
    port: 13080
    targetPort: 13080
    # nodePort: 30015 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  - name: https
    port: 13443
    targetPort: 13443
    # nodePort: 30017 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  selector:
    app: openncp-openatna
