apiVersion: apps/v1
kind: Deployment
metadata:
  name: openncp-openatna
  namespace: openncp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openncp-openatna
  template:
    metadata:
      labels:
        app: openncp-openatna
    spec:
      containers:
      - name: openncp-openatna
        image: docker.io/3ahealth/openncp-openatna:7.1.0
        ports:
        - containerPort: 13080
        - containerPort: 13443
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        # - name: EPSOS_PROPS_PATH
        #   value: "${EPSOS_PROPS_PATH}"
        - name: CATALINA_OPTS
          value: "
            -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties
            -Dfile.encoding=UTF-8"
        # - name: JAVA_OPTS
        #   value: "
        #     -DopenATNA.properties.path=file:/opt/epsos-configuration/ATNA_resources/openatna.properties
        #     -Dfile.encoding=UTF-8
        #     -Dmysql_host=${MYSQL_HOST}
        #     -Dmysql_port=${MYSQL_PORT}
        #     -Dmysql_username=${MYSQL_USERNAME}
        #     -Dmysql_password=${MYSQL_PASSWORD}
        #     -Dtls_key_alias=${TLS_KEY_ALIAS}
        #     -Dtls_keystore_pwd=${TLS_KEYSTORE_PWD}
        #     -Dtls_keystore_path=${TLS_KEYSTORE_PATH}
        #     -Dtls_truststore_pwd=${TLS_TRUSTSTORE_PWD}
        #     -Dtls_truststore_path=${TLS_TRUSTSTORE_PATH}"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        # volumeMounts:
        # - name: epsos-configuration
        #   mountPath: /opt/epsos-configuration
        # - name: openncp-openatna-logs
        #   mountPath: /usr/local/tomcat/logs
        # - name: openncp-certs
        #   mountPath: /usr/local/tomcat/opt/openncp-configuration/certs
      # volumes:
      # - name: epsos-configuration
      #   hostPath:
      #     path: /path/to/your/epsos-configuration  # Replace with actual path or use ConfigMap
      # - name: openncp-openatna-logs
      #   emptyDir: {}
      # - name: openncp-certs
      #   hostPath:
      #     path: /path/to/your/openncp-configuration/certs  # Replace with actual path or use Secret/ConfigMap