apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    # nodePort: 30250 # This is the port that will be exposed to the outside world (Adjust this to your needs)
  selector:
    app: mysql
