apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: openncp
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30250 # Expose the service on a static port
  selector:
    app: mysql
