apiVersion: batch/v1
kind: Job
metadata:
  name: openncp-configuration-utility
  namespace: openncp
spec:
  template:
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command: ['sh', '-c', 'until nc -z $MYSQL_HOST $MYSQL_PORT; do echo waiting for mysql; sleep 2; done;']
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
      containers:
      - name: openncp-configuration-utility
        image: docker.io/3ahealth/openncp-configuration-utility:7.1.0
        env:
        - name: MYSQL_HOST
          value: mysql-service
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        # volumeMounts:
        # - name: openncp-configuration-utility-data
        #   mountPath: /usr/local/openncp-configuration-utility
      restartPolicy: Never
      # volumes:
      # - name: openncp-configuration-utility-data
      #   hostPath:
      #     path: /path/to/your/openncp-configuration-utility
