apiVersion: v1
kind: ConfigMap
metadata:
  name: openncp-tsam-exporter-cm
data:
  application.yml: |
    debug: false
    spring:
      datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/ehealth_ltrdb?useSSL=false
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.jdbc.Driver
    openncp:
      root:
        path: ${EPSOS_PROPS_PATH}
